=== hardfalcon/VMG8825-D70B/platform/iad/driver/lantiq_drv_tapi-git/lantiq_drv_tapi/xml/drv_tapi_io.dtd
<!ELEMENT ioctls (ioctl+)>

<!ELEMENT ioctl (context?,states?,handler?,argument?,features?)>
<!ATTLIST ioctl name CDATA #REQUIRED>

<!ELEMENT context (#PCDATA)>

<!ELEMENT handler (#PCDATA)>
<!ATTLIST handler kind (high-level|low-level) #REQUIRED>

<!ELEMENT argument (#PCDATA)>
<!ATTLIST argument kind (pointer|integer) #REQUIRED>

<!ELEMENT features (feature+)>
<!ELEMENT feature (#PCDATA)>

<!ELEMENT states (state+)>
<!ELEMENT state (#PCDATA)>

=== hardfalcon/VMG8825-D70B/platform/iad/driver/lantiq_drv_tapi-git/lantiq_drv_tapi/xml/drv_tapi_qos_io.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ioctls SYSTEM "drv_tapi_io.dtd">
<!--

                              Copyright (c) 2014
                            Lantiq Deutschland GmbH

  For licensing information, see the file 'LICENSE' in the root folder of
  this software module.

-->
<!--
   \file drv_tapi_io.xml
   Description of TAPI v4 QOS ioctl handlers
-->
<ioctls>
   <ioctl name="FIO_QOS_START">
      <context>channel</context>
      <handler kind="high-level">IFX_TAPI_QOS_Start</handler>
      <argument kind="pointer">QOS_INIT_SESSION const</argument>
   </ioctl>
   <ioctl name="FIO_QOS_ON_SOCKET_START">
      <context>channel</context>
      <handler kind="high-level">IFX_TAPI_QOS_SessionOnSocketStart</handler>
      <argument kind="pointer">QOS_INIT_SESSION_ON_SOCKET const</argument>
   </ioctl>
   <ioctl name="FIO_QOS_ACTIVATE"/>
   <ioctl name="FIO_QOS_STOP">
      <context>channel</context>
      <handler kind="high-level">IFX_TAPI_QOS_Stop</handler>
   </ioctl>
   <ioctl name="FIO_QOS_CLEAN">
      <handler kind="high-level">IFX_TAPI_QOS_Clean</handler>
   </ioctl>
</ioctls>
